apiVersion: v1
kind: Pod
metadata:
  name: echo-v1
  labels:
    app: test
    version: v1
    name: echo-v1
spec:
  containers:
  - name: echo
    image: hashicorp/http-echo
    command: ["/http-echo"]
    args: ["-text", "hello world v1"]
    ports:
    - containerPort: 5678
---
apiVersion: v1
kind: Pod
metadata:
  name: echo-v2
  labels:
    app: test
    version: v2
    name: echo-v2
spec:
  containers:
  - name: echo
    image: hashicorp/http-echo
    command: ["/http-echo"]
    args: ["-text", "hello world v2"]
    ports:
    - containerPort: 5678
