/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	maegusv1beta1 "github.com/draveness/proxier/pkg/apis/maegus/v1beta1"
	internalinterfaces "github.com/draveness/proxier/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/draveness/proxier/pkg/client/listers/maegus/v1beta1"
	versioned "github.com/draveness/proxier/pkg/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ProxierInformer provides access to a shared informer and lister for
// Proxiers.
type ProxierInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ProxierLister
}

type proxierInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewProxierInformer constructs a new informer for Proxier type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProxierInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProxierInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredProxierInformer constructs a new informer for Proxier type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProxierInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MaegusV1beta1().Proxiers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MaegusV1beta1().Proxiers(namespace).Watch(options)
			},
		},
		&maegusv1beta1.Proxier{},
		resyncPeriod,
		indexers,
	)
}

func (f *proxierInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProxierInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *proxierInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&maegusv1beta1.Proxier{}, f.defaultInformer)
}

func (f *proxierInformer) Lister() v1beta1.ProxierLister {
	return v1beta1.NewProxierLister(f.Informer().GetIndexer())
}
