/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/draveness/proxier/pkg/apis/maegus/v1beta1"
	scheme "github.com/draveness/proxier/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProxiersGetter has a method to return a ProxierInterface.
// A group's client should implement this interface.
type ProxiersGetter interface {
	Proxiers(namespace string) ProxierInterface
}

// ProxierInterface has methods to work with Proxier resources.
type ProxierInterface interface {
	Create(*v1beta1.Proxier) (*v1beta1.Proxier, error)
	Update(*v1beta1.Proxier) (*v1beta1.Proxier, error)
	UpdateStatus(*v1beta1.Proxier) (*v1beta1.Proxier, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.Proxier, error)
	List(opts v1.ListOptions) (*v1beta1.ProxierList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Proxier, err error)
	ProxierExpansion
}

// proxiers implements ProxierInterface
type proxiers struct {
	client rest.Interface
	ns     string
}

// newProxiers returns a Proxiers
func newProxiers(c *MaegusV1beta1Client, namespace string) *proxiers {
	return &proxiers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the proxier, and returns the corresponding proxier object, and an error if there is any.
func (c *proxiers) Get(name string, options v1.GetOptions) (result *v1beta1.Proxier, err error) {
	result = &v1beta1.Proxier{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("proxiers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Proxiers that match those selectors.
func (c *proxiers) List(opts v1.ListOptions) (result *v1beta1.ProxierList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ProxierList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("proxiers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested proxiers.
func (c *proxiers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("proxiers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a proxier and creates it.  Returns the server's representation of the proxier, and an error, if there is any.
func (c *proxiers) Create(proxier *v1beta1.Proxier) (result *v1beta1.Proxier, err error) {
	result = &v1beta1.Proxier{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("proxiers").
		Body(proxier).
		Do().
		Into(result)
	return
}

// Update takes the representation of a proxier and updates it. Returns the server's representation of the proxier, and an error, if there is any.
func (c *proxiers) Update(proxier *v1beta1.Proxier) (result *v1beta1.Proxier, err error) {
	result = &v1beta1.Proxier{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("proxiers").
		Name(proxier.Name).
		Body(proxier).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *proxiers) UpdateStatus(proxier *v1beta1.Proxier) (result *v1beta1.Proxier, err error) {
	result = &v1beta1.Proxier{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("proxiers").
		Name(proxier.Name).
		SubResource("status").
		Body(proxier).
		Do().
		Into(result)
	return
}

// Delete takes name of the proxier and deletes it. Returns an error if one occurs.
func (c *proxiers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("proxiers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *proxiers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("proxiers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched proxier.
func (c *proxiers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Proxier, err error) {
	result = &v1beta1.Proxier{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("proxiers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
