// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1beta1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/draveness/proxier/pkg/apis/maegus/v1beta1.Proxier":       schema_pkg_apis_maegus_v1beta1_Proxier(ref),
		"github.com/draveness/proxier/pkg/apis/maegus/v1beta1.ProxierSpec":   schema_pkg_apis_maegus_v1beta1_ProxierSpec(ref),
		"github.com/draveness/proxier/pkg/apis/maegus/v1beta1.ProxierStatus": schema_pkg_apis_maegus_v1beta1_ProxierStatus(ref),
	}
}

func schema_pkg_apis_maegus_v1beta1_Proxier(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Proxier is the Schema for the proxiers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/draveness/proxier/pkg/apis/maegus/v1beta1.ProxierSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/draveness/proxier/pkg/apis/maegus/v1beta1.ProxierStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/draveness/proxier/pkg/apis/maegus/v1beta1.ProxierSpec", "github.com/draveness/proxier/pkg/apis/maegus/v1beta1.ProxierStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_maegus_v1beta1_ProxierSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ProxierSpec defines the desired state of Proxier",
				Properties: map[string]spec.Schema{
					"backends": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/draveness/proxier/pkg/apis/maegus/v1beta1.BackendSpec"),
									},
								},
							},
						},
					},
					"selector": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"object"},
							AdditionalProperties: &spec.SchemaOrBool{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"ports": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/draveness/proxier/pkg/apis/maegus/v1beta1.ProxierPort"),
									},
								},
							},
						},
					},
				},
				Required: []string{"backends", "ports"},
			},
		},
		Dependencies: []string{
			"github.com/draveness/proxier/pkg/apis/maegus/v1beta1.BackendSpec", "github.com/draveness/proxier/pkg/apis/maegus/v1beta1.ProxierPort"},
	}
}

func schema_pkg_apis_maegus_v1beta1_ProxierStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ProxierStatus defines the observed state of Proxier",
				Properties: map[string]spec.Schema{
					"phase": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}
