/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	maegusv1 "github.com/draveness/proxier/pkg/apis/maegus/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProxiers implements ProxierInterface
type FakeProxiers struct {
	Fake *FakeMaegusV1
	ns   string
}

var proxiersResource = schema.GroupVersionResource{Group: "maegus.com", Version: "v1", Resource: "proxiers"}

var proxiersKind = schema.GroupVersionKind{Group: "maegus.com", Version: "v1", Kind: "Proxier"}

// Get takes name of the proxier, and returns the corresponding proxier object, and an error if there is any.
func (c *FakeProxiers) Get(name string, options v1.GetOptions) (result *maegusv1.Proxier, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(proxiersResource, c.ns, name), &maegusv1.Proxier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*maegusv1.Proxier), err
}

// List takes label and field selectors, and returns the list of Proxiers that match those selectors.
func (c *FakeProxiers) List(opts v1.ListOptions) (result *maegusv1.ProxierList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(proxiersResource, proxiersKind, c.ns, opts), &maegusv1.ProxierList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &maegusv1.ProxierList{ListMeta: obj.(*maegusv1.ProxierList).ListMeta}
	for _, item := range obj.(*maegusv1.ProxierList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested proxiers.
func (c *FakeProxiers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(proxiersResource, c.ns, opts))

}

// Create takes the representation of a proxier and creates it.  Returns the server's representation of the proxier, and an error, if there is any.
func (c *FakeProxiers) Create(proxier *maegusv1.Proxier) (result *maegusv1.Proxier, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(proxiersResource, c.ns, proxier), &maegusv1.Proxier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*maegusv1.Proxier), err
}

// Update takes the representation of a proxier and updates it. Returns the server's representation of the proxier, and an error, if there is any.
func (c *FakeProxiers) Update(proxier *maegusv1.Proxier) (result *maegusv1.Proxier, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(proxiersResource, c.ns, proxier), &maegusv1.Proxier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*maegusv1.Proxier), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProxiers) UpdateStatus(proxier *maegusv1.Proxier) (*maegusv1.Proxier, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(proxiersResource, "status", c.ns, proxier), &maegusv1.Proxier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*maegusv1.Proxier), err
}

// Delete takes name of the proxier and deletes it. Returns an error if one occurs.
func (c *FakeProxiers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(proxiersResource, c.ns, name), &maegusv1.Proxier{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProxiers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(proxiersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &maegusv1.ProxierList{})
	return err
}

// Patch applies the patch and returns the patched proxier.
func (c *FakeProxiers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *maegusv1.Proxier, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(proxiersResource, c.ns, name, pt, data, subresources...), &maegusv1.Proxier{})

	if obj == nil {
		return nil, err
	}
	return obj.(*maegusv1.Proxier), err
}
